<?php
$play_count = 0;
$correct_guesses = 0;
$guess_high = 0;
$guess_low = 0;
echo "Guess a number between 1 and 10\n";
echo "You earn a point if your guess matches a random number generated by the computer\n";
function guessNumber() {
global $guess_high, $guess_low, $correct_guesses, $play_count;
$play_count++;
$num = rand(1, 10);
$guess = intval(readline(">> "));
echo "Round: $play_count\n";
echo "Your guess: $guess\n";
echo "Computer's number: $num\n";
if ($num === $guess) {
    echo "You earned a point!\n";
    $correct_guesses++;
} elseif ($num > $guess) {
    $guess_low++;
} elseif ($num < $guess) {
    $guess_high++;
}
}

for ($count = 1; $count <= 5; $count++) {
    guessNumber();
}

$percent_correct = $correct_guesses/$play_count * 100;

echo "After $play_count rounds, you guessed correctly $percent_correct% of the time.\n";
if ($guess_high > $guess_low) {
echo "When you guessed wrong, you tended to guess high.\n";
} else {
echo "When you guessed wrong, you tended to guess low.\n";
}